#!/bin/sh
# /etc/init.d/S99rbsm

case "$1" in
    start)
        echo "Starting RBSM"
        # nohup /root/drmtest -u 5 -s 1 &
        # dmesg | grep input
        # lspci -k
	ulimit -c unlimited
	echo "./core" > /proc/sys/kernel/core_pattern
        ;;
    stop)
        echo "Stopping RBSM"
        killall drmtest 
        ;;
    *)
        echo "Usage: /etc/init.d/rbsm {start|stop}"
        exit 1
        ;;
esac

exit 0
